cmake: Fix exporting APIs from openxr-loader in mingw
This adds openxr-loader.def in source list of openxr-loader.dll for
all toolchain in Windows platform and fixes linking with test programs.
Otherwise, all required APIs are not exported from the shared library
and compiling test programs shows following errors

ld.exe: list_json.cpp.obj(.text+0x686): undefined reference to `xrDestroyInstance'
ld.exe: list_json.cpp.obj(.text+0x96f): undefined reference to `xrCreateInstance'